name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build server.go
      working-directory: server

    - uses: actions/upload-artifact@v2
      with:
        name: server
        path: server/server

    - name: Test
      run: go test -v -short ./...
      working-directory: server

  deploy:
    if: github.event_name != 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: server

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: stldevs.com
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          source: "server/server"
          target: "~/server"

      - name: Restart
        uses: appleboy/ssh-action@master
        with:
          host: stldevs.com
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo service trees stop
            mv -f ~/server /opt/trees/server
            cd /opt/trees
            chmod +x server
            sudo service trees start
