name: Go

on:
  push:
    paths:
    - 'server/**'
    branches: [ master ]
  pull_request:
    paths:
    - 'server/**'
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build server/server.go

    - name: Test
      run: go test -v server/...
