# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 13
      - run: npm ci
        working-directory: ui
      - run: npm run build
        working-directory: ui
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ui/dist
  deploy:
    if: github.event_name != 'pull_request'
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: stldevs.com
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          source: "dist"
          target: "~/dist"

      - name: Restart
        uses: appleboy/ssh-action@master
        with:
          host: stldevs.com
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            rm -rf /opt/trees/dist
            mv ~/dist /opt/trees
